---
- name : dump vars
  hosts: localhost
  connection: local 
  tasks:
    - name: Print some debug
      vars: 
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars.application | to_nice_json }} 
        
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info